import {StyledEngineProvider, Theme, ThemeProvider} from "@mui/material/styles";
import {createTheme} from "@mui/material";
import {ReactNode} from "react";

/* This was generated by the MUI v5 codemod, used for custom theme variables.
Cabbage doesn't have any yet (thus the eslint exemption) - but I'm keeping it
because I think I'll want it eventually. 
 */
declare module '@mui/styles/defaultTheme' {
  // eslint-disable-next-line @typescript-eslint/no-empty-interface
  interface DefaultTheme extends Theme {
  }
}

// https://www.color-name.com/
export const Color = {
  onyx: "#343a40",
  darkCharcoal: "#333333",
  jet: "#343434",
}

/** use lightColor if light mode, otherwise use darkColor */
function lightDarkColor(
  theme: Theme,
  lightColor: string | undefined = undefined,
  darkColor: string | undefined = undefined
): string | undefined{
  return theme.palette.mode === 'light' ? lightColor : darkColor
}

export const mode = createTheme({
  palette: {
    mode: 'light',
  },
});

export const theme = createTheme(mode, {
  components: {
    MuiAppBar: {
      styleOverrides: {
        colorPrimary: {
          backgroundColor: lightDarkColor(mode, Color.onyx),
        }
      }
    }
  }
});

export function CabbageTheme({children}: { children: ReactNode }){
  // IMPROVE: get rid of StyledEngineProvider when everything is ported to 
  // Emotion and we can get rid of the @mui/styles package. 
  return <StyledEngineProvider injectFirst>
    <ThemeProvider theme={theme}>
      {children}
    </ThemeProvider>
  </StyledEngineProvider>
}