import {StyledEngineProvider, Theme, ThemeProvider} from "@mui/material/styles";
import {createTheme} from "@mui/material";
import {ReactNode} from "react";

/* This was generated by the MUI v5 codemod, used for custom theme variables.
Cabbage doesn't have any yet (thus the eslint exemption) - but I'm keeping it
because I think I'll want it eventually. 
 */
declare module '@mui/styles/defaultTheme' {
  // eslint-disable-next-line @typescript-eslint/no-empty-interface
  interface DefaultTheme extends Theme {
  }
}

export const Color = {
  navbarCharcoal: "#343a40",
  darkCharcoal: "#333333",
  // stolen from https://www.eggradients.com/color-names
  jet: "#343434",
}

/** use lightColor if light mode, otherwise use darkColor */
function lightDarkColor(
  theme: Theme,
  lightColor: string | undefined = undefined,
  darkColor: string | undefined = undefined
): string | undefined{
  return theme.palette.mode === 'light' ? lightColor : darkColor
}

export const modeTheme = createTheme({
  palette: {
    mode: 'light',
  },
})

export const theme = createTheme(modeTheme, {
  components: {
    MuiAppBar: {
      styleOverrides: {
        colorPrimary: {
          backgroundColor: lightDarkColor(modeTheme, Color.navbarCharcoal),
        }
      }
    }
  }
});

export function CabbageTheme({children}: { children: ReactNode }){
  // IMPROVE: get rid of StyledEngineProvider when everything is ported to 
  // Emotion and we can get rid of the @mui/styles package. 
  return <StyledEngineProvider injectFirst>
    <ThemeProvider theme={theme}>
      {children}
    </ThemeProvider>
  </StyledEngineProvider>
}