
-- schema did not get deleted when I did a SB restore database
-- somehow the restore doesn't delete the private schema
-- but it did delet the table within it?
create schema if not exists private;


create table private.cabbage_error (
  id integer generated by default as identity
    constraint cabbage_error_pkey primary key,
  content json not null
);

grant insert, select, update, delete, truncate, references, trigger on private.cabbage_error to supabase_auth_admin;
grant insert on private.cabbage_error to anon;


create or replace function public.store_error(json_content jsonb)
  returns void security definer
  language sql
as $$
  insert into private.cabbage_error (content) values(json_content);
$$;

grant execute on function public.store_error(jsonb) to anon;




