-- rename table and function and add received column

create table private.sentry_event (
  id integer generated by default as identity
    constraint sentry_event_pkey primary key,
  received timestamp without time zone not null,
  content json not null
);

grant insert, select, update, delete, truncate, references, trigger on private.sentry_event to supabase_auth_admin;
grant insert on private.sentry_event to anon;


create or replace function public.store_sentry_event(json_content jsonb)
  returns void security definer
  language sql
as $$
  insert into private.sentry_event (received, content)
  values(transaction_timestamp(), json_content);
$$;

grant execute on function public.store_sentry_event(jsonb) to anon;




